before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: tbls-meta-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/tbls-meta.version={{.Version}} -X github.com/k1LoW/tbls-meta.commit={{.FullCommit}} -X github.com/k1LoW/tbls-meta.date={{.Date}} -X github.com/k1LoW/tbls-meta/version.Version={{.Version}}
-
  id: tbls-meta-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/tbls-meta.version={{.Version}} -X github.com/k1LoW/tbls-meta.commit={{.FullCommit}} -X github.com/k1LoW/tbls-meta.date={{.Date}} -X github.com/k1LoW/tbls-meta/version.Version={{.Version}}
archives:
-
  id: tbls-meta-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - LICENSE
    - CREDITS
    - README.md
    - CHANGELOG.md
  rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
nfpms:
  -
    id: tbls-meta-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - tbls-meta-linux
    homepage: https://github.com/k1LoW/tbls-meta
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: tbls-meta is an external subcommand of tbls for applying metadata managed by tbls to the datasource.
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - tbls
    bindir: /usr/bin
    epoch: 1
